version: '3'
services:
  deployment:
    build: .
    image: humancellatlas/upload-service-deployment
    volumes:
      - ../..:/code
      - $HOME/.aws:/aws/host:ro
    environment:
      - AWS_PROFILE=${AWS_PROFILE}
      - DEPLOYMENT_STAGE=${DEPLOYMENT_STAGE}
